import { Inter } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "./context/ChartContext";
import { UserProvider } from "./context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ベトナム交流",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ChatProvider>{children}</ChatProvider>
        </UserProvider>
      </body>
    </html>
  );
}
